<?php

namespace app\admin\controller;

use app\BaseController;
use think\exception\HttpResponseException;

/**
 * 后台基础空值器
 * Class AdminBase
 * @package app\admin\controller
 */
class AdminBase extends BaseController
{

    public $adminUser = null;//默认属性值

    /**
     * 初始化
     * @author bjy
     */
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub

        //调取是否登录 --未登录，返回登录页  切换到中间件
//        if (empty($this->isLogin())) {
//            return $this->redirect(url("login/index"));
//        }
    }

    /**
     * 判断后台管理员是否登录
     * @return bool
     * @author bjy
     */
    public function isLogin()
    {
        //获取session内的用户信息
        $this->adminUser = session(config("admin.session_admin"));
        //为空则表示未登录
        if (empty($this->adminUser)) {
            return false;
        }
        //或者采取redis方式来存储及验证
        return true;
    }

    /**
     * 重定义 -- 跳转
     * @param mixed ...$args
     * @author bjy
     */
    public function redirect(...$args)
    {
        throw new HttpResponseException(redirect(...$args));
    }

}